#!/usr/bin/env python3
"""
RA causal-DAG motif-commit simulator v0.1

This simulator mirrors the vocabulary of RA_MotifCommitProtocol.lean:

  MotifCandidate
  CausalSupportCut / GraphSupportCut
  supportCutOfFiniteHasseFrontier
  ReadyAt
  CommitContext.supports
  CommitContext.incompatible
  CommitsAt
  FinalizedAtDepth

It is intentionally not a blockchain/consensus simulator. There are no agents,
votes, leaders, or message rounds. The core question is graph-native:

  Which motif candidates have certified support cuts whose support vertices lie
  in the causal past of a site, and which of those are excluded by certified-
  ready incompatible competitors?
"""
from __future__ import annotations

import argparse
import csv
import json
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, FrozenSet, Iterable, List, Mapping, Optional, Sequence, Set, Tuple


NodeId = int
SupportCut = FrozenSet[NodeId]


@dataclass(frozen=True)
class MotifCandidate:
    """Finite motif candidate with a carrier and a certified support cut.

    `exclusion_domain` is a simulator convenience for defining incompatibility:
    two certified candidates with the same non-null exclusion domain and distinct
    names are treated as incompatible by the default context.
    """

    name: str
    carrier: FrozenSet[NodeId]
    support_cut: SupportCut
    kind: str = "generic"
    exclusion_domain: Optional[str] = None
    certified: bool = True
    priority: int = 0
    metadata: Mapping[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class CommitDecision:
    motif: str
    site: NodeId
    supported: bool
    ready: bool
    commits: bool
    blocked_by: Tuple[str, ...] = ()


class CausalDAG:
    """Append-only finite DAG with edges oriented from causal past to future."""

    def __init__(self) -> None:
        self.parents: Dict[NodeId, Set[NodeId]] = {}
        self.children: Dict[NodeId, Set[NodeId]] = {}
        self.depth: Dict[NodeId, int] = {}
        self._next_id: int = 0

    def add_node(self, parents: Iterable[NodeId] = ()) -> NodeId:
        parent_set = set(parents)
        unknown = parent_set.difference(self.parents)
        if unknown:
            raise ValueError(f"unknown parent node(s): {sorted(unknown)}")
        node = self._next_id
        self._next_id += 1
        self.parents[node] = set(parent_set)
        self.children[node] = set()
        for p in parent_set:
            self.children[p].add(node)
        self.depth[node] = 0 if not parent_set else 1 + max(self.depth[p] for p in parent_set)
        return node

    @property
    def nodes(self) -> Tuple[NodeId, ...]:
        return tuple(sorted(self.parents))

    @property
    def edges(self) -> Tuple[Tuple[NodeId, NodeId], ...]:
        return tuple(sorted((p, c) for c, ps in self.parents.items() for p in ps))

    def maximal_nodes(self) -> Tuple[NodeId, ...]:
        return tuple(n for n in self.nodes if not self.children[n])

    def ancestors(self, node: NodeId, include_self: bool = False) -> FrozenSet[NodeId]:
        self._require_node(node)
        out: Set[NodeId] = {node} if include_self else set()
        stack = list(self.parents[node])
        while stack:
            p = stack.pop()
            if p not in out:
                out.add(p)
                stack.extend(self.parents[p])
        return frozenset(out)

    def descendants(self, node: NodeId, include_self: bool = False) -> FrozenSet[NodeId]:
        self._require_node(node)
        out: Set[NodeId] = {node} if include_self else set()
        stack = list(self.children[node])
        while stack:
            c = stack.pop()
            if c not in out:
                out.add(c)
                stack.extend(self.children[c])
        return frozenset(out)

    def reachable(self, src: NodeId, dst: NodeId) -> bool:
        """Reflexive/transitive reachability: src lies in the causal past of dst."""
        self._require_node(src)
        self._require_node(dst)
        return src == dst or src in self.ancestors(dst)

    def candidate_past_from_support(self, support: Iterable[NodeId]) -> FrozenSet[NodeId]:
        """Smallest down-closed past generated by a proposed support set."""
        past: Set[NodeId] = set()
        for s in support:
            self._require_node(s)
            past.update(self.ancestors(s, include_self=True))
        return frozenset(past)

    def is_down_closed(self, past: Iterable[NodeId]) -> bool:
        pset = set(past)
        for y in list(pset):
            if not self.ancestors(y).issubset(pset):
                return False
        return True

    def hasse_frontier(self, past: Iterable[NodeId]) -> SupportCut:
        """Maximal vertices of a downset under reflexive reachability."""
        pset = frozenset(past)
        unknown = set(pset).difference(self.parents)
        if unknown:
            raise ValueError(f"unknown past node(s): {sorted(unknown)}")
        if not self.is_down_closed(pset):
            raise ValueError("Hasse frontier requires a down-closed candidate past")
        frontier = {
            v for v in pset
            if not any(v != w and self.reachable(v, w) for w in pset)
        }
        return frozenset(frontier)

    def support_cut_of_finite_hasse_frontier(self, past: Iterable[NodeId]) -> SupportCut:
        """Python counterpart of `supportCutOfFiniteHasseFrontier`."""
        return self.hasse_frontier(past)

    def ready_at(self, support_cut: SupportCut, site: NodeId) -> bool:
        """Python counterpart of `GraphReadyAt`."""
        self._require_node(site)
        return all(self.reachable(y, site) for y in support_cut)

    def finalized_at_depth(self, support_cut: SupportCut, min_depth: int) -> bool:
        """Depth-indexed finality: all sites at depth >= min_depth are ready."""
        return all(
            self.ready_at(support_cut, x)
            for x, d in self.depth.items()
            if d >= min_depth
        )

    def _require_node(self, node: NodeId) -> None:
        if node not in self.parents:
            raise ValueError(f"unknown node: {node}")


class CommitContext:
    """Certified support and incompatibility context for motif commit."""

    def __init__(
        self,
        supports: Optional[Callable[[MotifCandidate, SupportCut], bool]] = None,
        incompatible: Optional[Callable[[MotifCandidate, MotifCandidate], bool]] = None,
    ) -> None:
        self.supports = supports or self.default_supports
        self.incompatible = incompatible or self.default_incompatible

    @staticmethod
    def default_supports(motif: MotifCandidate, support_cut: SupportCut) -> bool:
        return motif.certified and motif.support_cut == support_cut

    @staticmethod
    def default_incompatible(a: MotifCandidate, b: MotifCandidate) -> bool:
        return (
            a.name != b.name
            and a.exclusion_domain is not None
            and a.exclusion_domain == b.exclusion_domain
        )


class MotifCommitProtocol:
    """Strict RA motif-commit semantics over a CausalDAG."""

    def __init__(self, dag: CausalDAG, motifs: Sequence[MotifCandidate], context: Optional[CommitContext] = None) -> None:
        self.dag = dag
        self.motifs = list(motifs)
        self.context = context or CommitContext()

    def supported(self, motif: MotifCandidate) -> bool:
        return self.context.supports(motif, motif.support_cut)

    def ready(self, motif: MotifCandidate, site: NodeId) -> bool:
        return self.dag.ready_at(motif.support_cut, site)

    def blockers(self, motif: MotifCandidate, site: NodeId) -> Tuple[MotifCandidate, ...]:
        if not self.supported(motif) or not self.ready(motif, site):
            return ()
        blocked_by: List[MotifCandidate] = []
        for other in self.motifs:
            if other.name == motif.name:
                continue
            if not self.supported(other):
                continue
            if not self.ready(other, site):
                continue
            if self.context.incompatible(motif, other):
                blocked_by.append(other)
        return tuple(blocked_by)

    def decision(self, motif: MotifCandidate, site: NodeId) -> CommitDecision:
        supported = self.supported(motif)
        ready = self.ready(motif, site) if supported else False
        blocked = self.blockers(motif, site) if supported and ready else ()
        return CommitDecision(
            motif=motif.name,
            site=site,
            supported=supported,
            ready=ready,
            commits=supported and ready and not blocked,
            blocked_by=tuple(b.name for b in blocked),
        )

    def decisions_at(self, site: NodeId) -> Tuple[CommitDecision, ...]:
        return tuple(self.decision(m, site) for m in self.motifs)

    def committed_at(self, site: NodeId) -> Tuple[MotifCandidate, ...]:
        return tuple(m for m in self.motifs if self.decision(m, site).commits)


def generate_growth_demo(
    steps: int = 24,
    seed: int = 17,
    max_parents: int = 3,
    conflict_rate: float = 0.30,
) -> Tuple[CausalDAG, List[MotifCandidate], List[dict[str, object]]]:
    """Generate a small append-only RA causal-DAG and motif-candidate stream.

    The demo deliberately includes occasional incompatible alternatives so that
    the strict exclusion rule is visible: if two certified-ready motifs occupy
    the same exclusion domain at a site, neither one commits under the Lean-style
    `CommitsAt` predicate.
    """
    rng = random.Random(seed)
    dag = CausalDAG()
    genesis = dag.add_node()
    motifs: List[MotifCandidate] = []
    rows: List[dict[str, object]] = []

    # Genesis seed motif: empty support is immediately ready at every site.
    motifs.append(MotifCandidate(
        name="genesis_seed",
        carrier=frozenset({genesis}),
        support_cut=frozenset(),
        kind="seed",
        exclusion_domain=None,
    ))

    for _ in range(steps):
        existing = list(dag.nodes)
        frontier = list(dag.maximal_nodes()) or existing
        parent_pool = frontier if len(frontier) >= 1 else existing
        k = rng.randint(1, min(max_parents, len(parent_pool)))
        parents = set(rng.sample(parent_pool, k=k))

        # Occasionally add one non-maximal parent to make the Hasse-frontier
        # extraction visibly remove redundant support.
        if len(existing) > 2 and rng.random() < 0.35:
            parents.add(rng.choice(existing))

        site = dag.add_node(parents)
        past = dag.candidate_past_from_support(parents)
        support_cut = dag.support_cut_of_finite_hasse_frontier(past)

        stable = MotifCandidate(
            name=f"renewal_{site}",
            carrier=frozenset({site}),
            support_cut=support_cut,
            kind="renewal",
            exclusion_domain=None,
            metadata={"parents": sorted(parents), "past_size": len(past)},
        )
        motifs.append(stable)

        introduced_conflict = rng.random() < conflict_rate
        if introduced_conflict:
            domain = f"choice_at_{site}"
            motifs.append(MotifCandidate(
                name=f"choice_A_{site}",
                carrier=frozenset({site}),
                support_cut=support_cut,
                kind="alternative",
                exclusion_domain=domain,
                priority=1,
            ))
            motifs.append(MotifCandidate(
                name=f"choice_B_{site}",
                carrier=frozenset({site}),
                support_cut=support_cut,
                kind="alternative",
                exclusion_domain=domain,
                priority=1,
            ))

        protocol = MotifCommitProtocol(dag, motifs)
        decisions = protocol.decisions_at(site)
        committed = [d.motif for d in decisions if d.commits]
        blocked = [d.motif for d in decisions if d.ready and not d.commits and d.blocked_by]
        rows.append({
            "site": site,
            "depth": dag.depth[site],
            "parents": sorted(parents),
            "candidate_past_size": len(past),
            "hasse_frontier_support_cut": sorted(support_cut),
            "introduced_conflict": introduced_conflict,
            "ready_count": sum(1 for d in decisions if d.ready),
            "committed_count": len(committed),
            "blocked_count": len(blocked),
            "committed_motifs": committed,
            "blocked_ready_motifs": blocked,
        })

    return dag, motifs, rows


def rows_to_csv(rows: Sequence[Mapping[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "site", "depth", "parents", "candidate_past_size",
        "hasse_frontier_support_cut", "introduced_conflict",
        "ready_count", "committed_count", "blocked_count",
        "committed_motifs", "blocked_ready_motifs",
    ]
    with path.open('w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            out = dict(row)
            for key in ["parents", "hasse_frontier_support_cut", "committed_motifs", "blocked_ready_motifs"]:
                out[key] = json.dumps(out.get(key, []))
            writer.writerow(out)


def dump_state_json(dag: CausalDAG, motifs: Sequence[MotifCandidate], rows: Sequence[Mapping[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "nodes": list(dag.nodes),
        "edges": [list(e) for e in dag.edges],
        "depth": {str(k): v for k, v in dag.depth.items()},
        "motifs": [
            {
                "name": m.name,
                "carrier": sorted(m.carrier),
                "support_cut": sorted(m.support_cut),
                "kind": m.kind,
                "exclusion_domain": m.exclusion_domain,
                "certified": m.certified,
                "priority": m.priority,
                "metadata": dict(m.metadata),
            }
            for m in motifs
        ],
        "site_summaries": list(rows),
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the RA causal-DAG motif-commit simulator demo.")
    parser.add_argument('--steps', type=int, default=24)
    parser.add_argument('--seed', type=int, default=17)
    parser.add_argument('--max-parents', type=int, default=3)
    parser.add_argument('--conflict-rate', type=float, default=0.30)
    parser.add_argument('--csv', type=Path, default=Path('outputs/ra_causal_dag_demo_summary.csv'))
    parser.add_argument('--json', type=Path, default=Path('outputs/ra_causal_dag_demo_state.json'))
    args = parser.parse_args()

    dag, motifs, rows = generate_growth_demo(
        steps=args.steps,
        seed=args.seed,
        max_parents=args.max_parents,
        conflict_rate=args.conflict_rate,
    )
    rows_to_csv(rows, args.csv)
    dump_state_json(dag, motifs, rows, args.json)
    print(f"nodes={len(dag.nodes)} edges={len(dag.edges)} motifs={len(motifs)}")
    print(f"summary_csv={args.csv}")
    print(f"state_json={args.json}")
    if rows:
        print("last_site_summary=" + json.dumps(rows[-1], sort_keys=True))


if __name__ == '__main__':
    main()
