#!/usr/bin/env python3
"""Extract per-paper \bibitem entries into a consolidated audit CSV/BibTeX seed.

This script does not try to perform perfect bibliography conversion. It creates
an auditable inventory and a conservative `@misc` seed file preserving the
existing rendered citation text in a note field. Use the CSV to manually promote
entries to fully structured BibTeX records.
"""
from __future__ import annotations

import argparse
import csv
import datetime as _dt
import re
from collections import OrderedDict, defaultdict
from pathlib import Path
from typing import Dict, List, Sequence, Optional

BIBITEM_RE = re.compile(r"\\bibitem\s*(?:\[[^\]]*\])?\s*\{([^{}]+)\}")
THEBIB_START_RE = re.compile(r"\\begin\{thebibliography\}")
THEBIB_END_RE = re.compile(r"\\end\{thebibliography\}")


def tex_escape_bib_value(s: str) -> str:
    # Preserve TeX markup, but make the value safe as a BibTeX braced string.
    return s.replace("\n", " ").replace("\r", " ").strip()


def find_tex_files(papers_dir: Path) -> List[Path]:
    return sorted(
        p for p in papers_dir.glob("RA_Paper_*.tex")
        if p.is_file() and not p.name.endswith("_rakb_ids.tex") and "RAKB_TeX_RAKB_IDs" not in p.parts
    )


def extract_from_file(path: Path) -> List[dict]:
    text = path.read_text(encoding="utf-8")
    rows = []
    start = THEBIB_START_RE.search(text)
    end = THEBIB_END_RE.search(text)
    if not start or not end or end.start() <= start.end():
        return rows
    body = text[start.end():end.start()]
    matches = list(BIBITEM_RE.finditer(body))
    for i, m in enumerate(matches):
        key = m.group(1).strip()
        entry_start = m.end()
        entry_end = matches[i+1].start() if i+1 < len(matches) else len(body)
        raw = body[entry_start:entry_end].strip()
        raw = re.sub(r"\s+", " ", raw)
        rows.append({
            "source_tex": path.name,
            "bibitem_key": key,
            "raw_bibitem_text": raw,
        })
    return rows


def write_csv(path: Path, rows: List[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["source_tex", "bibitem_key", "raw_bibitem_text", "duplicate_key_count", "variant_count_for_key"]
    with path.open("w", newline="", encoding="utf-8") as fh:
        wr = csv.DictWriter(fh, fieldnames=fields)
        wr.writeheader()
        for r in rows:
            wr.writerow({k: r.get(k, "") for k in fields})


def write_seed_bib(path: Path, grouped: Dict[str, List[dict]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("% Auto-extracted seed bibliography from the canonical RA paper suite.")
    lines.append("% Generated by rakb_extract_bibitems.py.")
    lines.append("% These @misc entries preserve existing \\bibitem text for audit.")
    lines.append("% Promote entries to structured @article/@book/@misc records after manual verification.\n")
    for key, rows in grouped.items():
        notes = []
        seen = set()
        for r in rows:
            note = f"[{r['source_tex']}] {r['raw_bibitem_text']}"
            if note not in seen:
                seen.add(note)
                notes.append(note)
        lines.append(f"@misc{{{key},")
        lines.append(f"  title = {{{key}}},")
        lines.append("  author = {{Bibliography item pending structured conversion}},")
        lines.append("  year = {{n.d.}},")
        lines.append("  note = {" + tex_escape_bib_value(" ; ".join(notes)) + "},")
        lines.append("  keywords = {ra-imported-bibitem, needs-verification}")
        lines.append("}\n")
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Extract RA paper thebibliography entries into a consolidated audit CSV and BibTeX seed.")
    ap.add_argument("--repo", default=".")
    ap.add_argument("--papers", default="docs/RA_Canonical_Papers")
    ap.add_argument("--out", default="docs/RA_Canonical_Papers/RAKB_TeX_RAKB_IDs_Apr28_2026/reports")
    ap.add_argument("--bib-out", default="docs/RA_Canonical_Papers/common/ra_references_seed_from_bibitems.bib")
    args = ap.parse_args(argv)

    repo = Path(args.repo).resolve()
    papers_dir = (repo / args.papers).resolve() if not Path(args.papers).is_absolute() else Path(args.papers)
    out_dir = (repo / args.out).resolve() if not Path(args.out).is_absolute() else Path(args.out)
    bib_out = (repo / args.bib_out).resolve() if not Path(args.bib_out).is_absolute() else Path(args.bib_out)

    rows = []
    for tex in find_tex_files(papers_dir):
        rows.extend(extract_from_file(tex))

    grouped = OrderedDict()
    for r in rows:
        grouped.setdefault(r["bibitem_key"], []).append(r)

    variants = {}
    for key, rs in grouped.items():
        variants[key] = len(set(r["raw_bibitem_text"] for r in rs))
    for r in rows:
        r["duplicate_key_count"] = len(grouped[r["bibitem_key"]])
        r["variant_count_for_key"] = variants[r["bibitem_key"]]

    write_csv(out_dir / "rakb_bibitem_inventory.csv", rows)
    write_seed_bib(bib_out, grouped)

    report = f"""# RA bibliography extraction report

Generated: `{_dt.datetime.now().isoformat(timespec='seconds')}`

- TeX files scanned: {len(find_tex_files(papers_dir))}
- Bibitems found: {len(rows)}
- Unique keys: {len(grouped)}
- Keys with variants across papers: {sum(1 for v in variants.values() if v > 1)}

CSV inventory:

```text
{out_dir / 'rakb_bibitem_inventory.csv'}
```

BibTeX seed:

```text
{bib_out}
```

The seed file is intentionally conservative. It preserves existing citation text in `note` fields and should be manually converted to structured BibTeX before replacing paper bibliographies.
"""
    (out_dir / "rakb_bibitem_extraction_report.md").write_text(report, encoding="utf-8")
    print(report)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
